project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "img/"
  output-dir: docs
  
website:
  title: "Time Series Application"
  site-url: https://stats-tgeorge.github.io/STA364_TSApps/
  sidebar:
    background: "#BBBCBC"
    logo: "img/favicon.png" # This is where I put my hex
    pinned: true
    align: center
    tools:
      - icon: code-square
        href: http://turing.cornellcollege.edu:8787/
        text: "RStudio Server"
      - icon: book
        href: https://otexts.com/fpp3/
        text: "Book"
      - icon: person-fill
        text: "Moodle"
        menu:
          - text: Announcements
            url: https://moodle.cornellcollege.edu/mod/forum/view.php?id=296639
          - text: Gradebook
            url: https://moodle.cornellcollege.edu/grade/report/grader/index.php?id=8175
          - text: Homepage
            url: https://moodle.cornellcollege.edu/course/view.php?id=8175
      - icon: calendar
        href: https://calendar.google.com/calendar/u/0?cid=Y19mNDVlZjMyN2U1NjgzNWEwMjU3ODk4MGRjYTkyYWNhOWYzY2ExNmQxMWE2ODgxMGZhMzQ2ZTRlM2FiOGY1NzQ0QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20
        text: Course Calendar

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Course Contents"
        contents:
          - href: index.qmd
            text: Schedule & Assignments
          - href: course-links.qmd
            text: Useful links
          - href: project/project_scrollytelling_desc.qmd
            text: Project
      #     - href: project/1-working-collaboratively.qmd
      #       text: Working Together Lab
            
      - section: "Course information"
        contents:
          - href: syllabus.qmd
            text: Syllabus
          - href: course-overview.qmd
            text: Overview
          - href: https://stats-tgeorge.github.io/personal_website/course-support.html
            text: Support
          - href: course-instructor.qmd
            text: Instructor
          - href: computing-access.qmd
            text: R/RStudio Access
     
  page-footer:
    left: "Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})"
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  favicon: "/img/favicon.png"
    
format:
  html:
    theme:
      light: 
        - united
        - style.scss 
      dark: darkly
    toc: true
    highlight-style: monokai

execute:
  freeze: true


    

