- name: "Forecasting Earthquakes"
  href: "student_examples/Alexa Brown.html"
  author: "Alexa Brown"
  
- name: "A history of Visitors of the first World’s Fairs"
  href: "student_examples/Ella Henze.html"
  author: "Ella Henze"
  
- name: "The Increase of NFL Player Weights Over Time"
  href: "student_examples/Garrett Roehl.html"
  author: "Garrett Roehl"
  
- name: "The Phantom of the Opera: 1888 to 2020"
  href: "student_examples/Iris Carroll.html"
  author: "Iris Carroll"
  
- name: "The Rise of Major League Baseball Salaries"
  href: "student_examples/Jack Rogers.html"
  author: "Jack Rogers"
  
- name: "Airline Baggage Complaints"
  href: "student_examples/Joe Wald.html"
  author: "Joe Wald"
  
- name: "What is Climate Change"
  href: "student_examples/Liam Borer.html"
  author: "Liam Borer-Seabloom"
  
- name: "Ireland Surface Temperature and Climate Change"
  href: "student_examples/Sophie Brown.html"
  author: "Sophie Brown"
  
- name: "UFOs Sighting and Media"
  href: "student_examples/Oscar Schaubert.html"
  author: "Oscar Schaubert"
  
  