---
title: "Homework 3"
subtitle: "Time Series Decomposition"
eval: false
---

```{r}
#| eval: true
#| include: false
library(tidyverse)
library(fpp3)
```

# Getting started

## R/Rstudio in Class

-   Go to our RStudio Server at <http://turing.cornellcollege.edu:8787/>

### Each of your assignments will begin with the following setup steps.

-   Finding the instructions on our website: <https://stats-tgeorge.github.io/STA363_AdvReg/>

-   Going to our RStudio Server at <http://turing.cornellcollege.edu:8787/>

-   Open the respective file from the shared STA364_inst_files folder mentioned above. It will be named something like *hw-02_LAST_NAME.qmd*.

-   Then you need to save your copy. Click *File -\> Save as -\> Navigate to the folder `STA364_Projects` (that we share) -\> Change the "LAST_NAME part of the file name to your last name -\> Save*.

-   Update the top of the document, called the `YAML,` with your name.

# Homework Instructions

Be sure to include the relevant R code and complete sentences answering each question (e.g., if I ask for the average, you can output the answer in R but **also** write a complete sentence with the answer). Be sure to save your files frequently!

Data for the homework will be in the STA364_inst_files -\> data folder.

# Exercises

## Reading

None.

## Problems



Problems: Chapter 2.10 problems: 7-10
From this point forward - you need to start commenting on your graphs. What do you observe? Is there trends/cycles/seasonal effects? Outliers? Other interesting features? 




### Question 1

### Question 2 (fpp3)


### Question 3 (fpp4)

### Question 4 (fpp6)


















# Submission

When you are finished with your homework, be sure to Render the final document. Once rendered, you can download your file by:

-   Finding the .html file in your File pane of RStudio (on the bottom right of the screen)
-   Click the check box next to the file
-   Click the blue gear above and then click "Export" to download
-   Submit your final HTML document to the respective assignment on [Moodle]({{< var course.moodle >}})
